# Generated by Django 2.0 on 2018-02-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_add_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastro',
            name='commentOpen',
            field=models.TextField(blank=True, null=True, verbose_name='comment open'),
        ),
    ]
