# Generated by Django 2.0 on 2018-02-11 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0003_gastro_commentopen'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastro',
            name='last_editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='last editor'),
        ),
        migrations.AlterField(
            model_name='gastro',
            name='cafe',
            field=models.BooleanField(default=False, verbose_name='Café'),
        ),
        migrations.RemoveField(
            model_name='gastro',
            name='closed',
        ),
        migrations.AddField(
            model_name='gastro',
            name='closed',
            field=models.DateField(default=None, null=True, verbose_name='closed'),
        ),
        migrations.AlterField(
            model_name='gastro',
            name='closingSun',
            field=models.TimeField(blank=True, null=True, verbose_name='closing sunday'),
        ),
        migrations.AlterField(
            model_name='gastro',
            name='commentOpen',
            field=models.TextField(blank=True, null=True, verbose_name='comment opening hours'),
        ),
        migrations.AlterField(
            model_name='gastro',
            name='district',
            field=models.CharField(choices=[('CHARLOTTENBURG', 'Charlottenburg'), ('FRIEDRICHSHAIN', 'Friedrichshain'), ('HELLERSDORF', 'Hellersdorf'), ('HOHENSCHÖNHAUSEN', 'Hohenschönhausen'), ('KREUZBERG', 'Kreuzberg'), ('KÖPENICK', 'Köpenick'), ('LICHTENBERG', 'Lichtenberg'), ('MARZAHN', 'Marzahn'), ('MITTE', 'Mitte'), ('NEUKÖLLN', 'Neukölln'), ('PANKOW', 'Pankow'), ('PRENZLAUER BERG', 'Prenzlauer Berg'), ('REINICKENDORF', 'Reinickendorf'), ('SCHÖNEBERG', 'Schöneberg'), ('SPANDAU', 'Spandau'), ('STEGLITZ', 'Steglitz'), ('TEMPELHOF', 'Tempelhof'), ('TIERGARTEN', 'Tiergarten'), ('TREPTOW', 'Treptow'), ('WEDDING', 'Wedding'), ('WEISSENSEE', 'Weißensee'), ('WILMERSDORF', 'Wilmersdorf'), ('ZEHLENDORF', 'Zehlendorf')], max_length=30, null=True, verbose_name='district'),
        ),
        migrations.AlterField(
            model_name='gastro',
            name='dog',
            field=models.NullBooleanField(choices=[(None, 'unknown'), (True, 'yes'), (False, 'no')], verbose_name='dogs allowed'),
        ),
        migrations.AlterField(
            model_name='gastro',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='gastro',
            name='openingSun',
            field=models.TimeField(blank=True, null=True, verbose_name='opening sunday'),
        ),
    ]
