name: Build image
description: Build image with given context and naming

inputs:
  image-type:
    description: "Type of image (be/fe)"
    required: true
  image-context:
    description: "Context of the image"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Log in to the Container registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Image
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ghcr.io/bvdata-${{ github.event.inputs.image-type }}
        tags: |
          type=sha
          type=raw,value=latest

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ${{ github.event.inputs.image-context }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        no-cache: true
