name: Build image
description: Build image with given context and naming

inputs:
  imageType:
    description: "Type of image (be/fe)"
    required: true
  imageContext:
    description: "Context of the image"
    required: true
  repoToken:
    description: "Github Token"
    required: true
  buildArgs:
    description: Build args
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Log in to the Container registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ inputs.repoToken }}

    - name: Extract metadata (tags, labels) for Image
      id: meta
      uses: docker/metadata-action@v3
      with:
        images:  ${{ env.REGISTRY }}/${{ env.REPO }}/${{ inputs.imageType }}
        tags: |
          type=sha
          type=raw,value=latest
    if: "${{ inputs.buildArgs == '' }}"
    - name: Build and push Docker image without buildArgs
      uses: docker/build-push-action@v2
      with:
        context: ${{ inputs.imageContext }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        no-cache: true
    if: "${{ inputs.buildArgs != '' }}"
      - name: Build and push Docker image with buildArgs
        uses: docker/build-push-action@v2
        with:
          context: ${{ inputs.imageContext }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          no-cache: true
          build-args: ${{ inputs.buildArgs }}
