files: ^backend/
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    - id: debug-statements
    - id: check-added-large-files
    - id: trailing-whitespace
    - id: check-docstring-first
    - id: check-merge-conflict

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
    -   id: flake8
        args: [--config=backend/tox.ini]

-   repo: https://github.com/PyCQA/isort
    rev: 5.5.2
    hooks:
    -   id: isort
        args: [--settings=backend/.isort.cfg]

-   repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
    - id: black
