version: '3.4'

services:
    django:
        build: .
        restart: always
        depends_on:
            - postgres
        ports:
            - 8000:8000
        volumes:
            - ./static:/code/static
        environment:
            - PORT=8000

            - DATABASE_NAME=${DBNAME}
            - DATABASE_USER=${DBUSER}
            - DATABASE_PASSWORD=${DBPASSWORD}

            - SECRET_KEY=${SECRET_KEY}
    postgres:
        image: postgres:10.1-alpine
        restart: always
        volumes:
            - pgdata:/var/lib/postgresql/data/
        environment:
            - POSTGRES_DB=${DBNAME}
            - POSTGRES_USER=${DBUSER}
            - POSTGRES_PASSWORD=${DBPASSWORD}
volumes:
  pgdata:
