version: '3.4'

services:
    django:
        build: .
        restart: always
        depends_on:
            - postgres
        ports:
            - 8000:8000
        volumes:
            - ./static:/app/static
        env_file:
            - .env
    postgres:
        image: postgres:10.1-alpine
        restart: always
        volumes:
            - pgdata:/var/lib/postgresql/data/
        environment:
            - POSTGRES_DB=${DATABASE_NAME}
            - POSTGRES_USER=${DATABASE_USER}
            - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
volumes:
  pgdata:
