version: '3.4'

services:
    backend:
        image: bvdata-be
        build:
            context: ./backend/
            target: builder-base
            args:
                ENVIRONMENT: dev
        depends_on:
            - postgres
        env_file:
            - .env
        volumes:
            - ./backend/:/app
        command: python /app/manage.py runserver 0.0.0.0:8000
        expose:
            - 8000
        ports:
            - "8000:8000"
    frontend:
        image: bvdata-fe
        build:
            context: ./frontend/
            target: prepare
            args:
                ENVIRONMENT: dev
        depends_on:
            - backend
        environment:
            - REACT_APP_MAP_API_URL=${REACT_APP_MAP_API_URL}
            - REACT_APP_SENTRY_DSN=${REACT_APP_SENTRY_DSN}
        volumes:
            - ./frontend/admin:/app
            - /app/node_modules
        command: yarn run dev
        expose:
            - 5173
        ports:
            - "5173:5173"
    postgres:
        image: postgres:14.2-alpine
        volumes:
            - pgdata:/var/lib/postgresql/data/
        environment:
            - POSTGRES_DB=${DATABASE_NAME}
            - POSTGRES_USER=${DATABASE_PASSWORD}
            - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    mailhog:
        image: mailhog/mailhog
        ports:
            - "8025:8025"

volumes:
  pgdata:
