version: '3'

services:
    django:
        build: .
        restart: always
        depends_on:
            - postgres
        ports:
            - 8000:8000
        volumes:
            - .:/code
        environment:
            - PORT=8000
            - DATABASE_URL=postgres://${DBPASSWORD}:${DBNAME}@postgres:5432/${DBUSER}

            - DATABASE_NAME=${DBNAME}
            - DATABASE_USER=${DBUSER}
            - DATABASE_PASSWORD=${DBPASSWORD}

            - SECRET_KEY=${SECRET_KEY}
            - DEBUG=${DEBUG}
            - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    postgres:
        image: postgres:10.1-alpine
        restart: always
        volumes:
            - pgdata:/var/lib/postgresql/data/
        environment:
            - POSTGRES_DB=${DBNAME}
            - POSTGRES_USER=${DBUSER}
            - POSTGRES_PASSWORD=${DBPASSWORD}
volumes:
  pgdata:
