version: '3.4'

services:
    django:
        build: .
        restart: always
        depends_on:
            - postgres
        volumes:
            - dstatic:/app/static
        env_file:
            - .env
    postgres:
        image: postgres:10.1-alpine
        restart: always
        volumes:
            - pgdata:/var/lib/postgresql/data/
        environment:
            - POSTGRES_DB=${DATABASE_NAME}
            - POSTGRES_USER=${DATABASE_USER}
            - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    entrypoint:
        image: nginx:stable-alpine
        restart: always
        ports:
            - 8000:8080
        volumes:
            - ./nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
            - dstatic:/var/www/dstatic
        depends_on:
            - django

volumes:
  pgdata:
  dstatic:
