version: '3.4'

services:
    postgres:
        image: postgres:10.1-alpine
        volumes:
            - pgdata:/var/lib/postgresql/data/
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        ports:
            - "5432:5432"
    redis:
        image: "redis:alpine"
        ports:
            - "6379:6379"
volumes:
  pgdata:
