version: '3.4'

services:
    django:
        build: .
        restart: always
        depends_on:
            - postgres
        ports:
            - 8000:8000
        volumes:
            - ./static:/code/static
        environment:
            - PORT=8000

            - DATABASE_NAME=${DBNAME}
            - DATABASE_USER=${DBUSER}
            - DATABASE_PASSWORD=${DBPASSWORD}

            - SECRET_KEY=${SECRET_KEY}

            - ADMINS=${ADMINS}

            - SERVER_EMAIL=${SERVER_EMAIL}
            - EMAIL_HOST=${EMAIL_HOST}
            - EMAIL_PORT=${EMAIL_PORT}
            - EMAIL_HOST_USER=${EMAIL_HOST_USER}
            - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
            - EMAIL_FROM=${EMAIL_FROM}
            - EMAIL_GASTROS=${EMAIL_GASTROS}
    postgres:
        image: postgres:10.1-alpine
        restart: always
        volumes:
            - pgdata:/var/lib/postgresql/data/
        environment:
            - POSTGRES_DB=${DBNAME}
            - POSTGRES_USER=${DBUSER}
            - POSTGRES_PASSWORD=${DBPASSWORD}
volumes:
  pgdata:
