version: '3.4'

services:
    backend:
        image: bvdata-be
        build:
            context: ./backend/
            target: builder-base
            args:
                ENVIRONMENT: dev
        depends_on:
            - postgres
        env_file:
            - ./backend/.env
        volumes:
            - ./backend/:/app
        command: python /app/manage.py runserver 0.0.0.0:8000
        expose:
            - 8000
        ports:
            - "8000:8000"
    frontend:
        image: bvdata-fe
        build:
            context: ./frontend/admin/
            target: prepare
            args:
                ENVIRONMENT: dev
        depends_on:
            - backend
        volumes:
            - ./frontend/admin:/app
            - /app/node_modules
        command: yarn run start
        expose:
            - 3000
        ports:
            - "3000:3000"
    postgres:
        image: postgres:10.1-alpine
        volumes:
            - pgdata:/var/lib/postgresql/data/
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    mailhog:
        image: mailhog/mailhog
        ports:
            - "8025:8025"

volumes:
  pgdata:
