#!/usr/bin/env bash

set -eo pipefail

function _isort {
  isort "$@"
}
function _black {
  black "$@"
}
function _flake8 {
  flake8 "$@"
}

function lint {
  # Lint code
  _isort "."
  _black "."
  _flake8 "."
}

function test-lint {
  # Check code linting during tests
  _isort "."
  _flake8 "."
  _black "--check" "."
}

function test {
  # Run all necessary tests
  test-lint
  pytest
}

function prod {
  python manage.py migrate
  python manage.py compilemessages -l de
  python manage.py collectstatic --noinput
  gunicorn -w 2 --bind 0.0.0.0:8000 --access-logfile - bvdata.wsgi
}

function help {
  printf "%s <task> [args]\n\nTasks:\n" "${0}"

  compgen -A function | grep -v "^_" | cat -n

  printf "\nExtended help:\n  Each task has comments for general usage\n"
}

# This idea is heavily inspired by: https://github.com/adriancooney/Taskfile
TIMEFORMAT=$'\nTask completed in %3lR'
time "${@:-help}"
