export type GastroDataType = {
  latitude: number;
  longitude: number;
  telephone: string;
  website: string;
  email: string;
  openingMon: null | string;
  closingMon: null | string;
  openingTue: null | string;
  closingTue: null | string;
  openingWed: null | string;
  closingWed: null | string;
  openingThu: null | string;
  closingThu: null | string;
  openingFri: null | string;
  closingFri: null | string;
  openingSat: null | string;
  closingSat: null | string;
  openingSun: null | string;
  closingSun: null | string;
  comment: string;
  commentEnglish: string;
  reviewLink: null | string;
  closed: boolean;
  textIntern: string;
  district: string;
  publicTransport: string;
  handicappedAccessible: null | boolean;
  handicappedAccessibleWc: null | boolean;
  dog: null | boolean;
  childChair: null | boolean;
  catering: null | boolean;
  delivery: null | boolean;
  organic: null | boolean;
  wlan: null | boolean;
  glutenFree: null | boolean;
  breakfast: null | boolean;
  brunch: null | boolean;
  seatsOutdoor: number;
  seatsIndoor: number;
  restaurant: boolean;
  imbiss: boolean;
  eiscafe: boolean;
  cafe: boolean;
  bar: boolean;
  commentOpen: string;
  hasSticker: boolean;
  name: string;
  street: string;
  cityCode: string;
  city: string;
  vegan: number;
  isSubmission: boolean;
  created: string;
  updated: string;
  idString: string;
  lastEditor: null | string;
};
