export const veganFieldOptions: Array<[number, string]> = [
  [2, 'Ominvore (vegan labeled)'],
  [4, 'Vegetarian (vegan labeled)'],
  [5, 'Vegan'],
];

export const districtFieldOptions: Array<[string, string]> = [
  ['CHARLOTTENBURG', 'Charlottenburg'],
  ['FRIEDRICHSHAIN', 'Friedrichshain'],
  ['HELLERSDORF', 'Hellersdorf'],
  ['HOHENSCHÖNHAUSEN', 'Hohenschönhausen'],
  ['KREUZBERG', 'Kreuzberg'],
  ['KÖPENICK', 'Köpenick'],
  ['LICHTENBERG', 'Lichtenberg'],
  ['MARZAHN', 'Marzahn'],
  ['MITTE', 'Mitte'],
  ['NEUKÖLLN', 'Neukölln'],
  ['PANKOW', 'Pankow'],
  ['PRENZLAUER BERG', 'Prenzlauer Berg'],
  ['REINICKENDORF', 'Reinickendorf'],
  ['SCHÖNEBERG', 'Schöneberg'],
  ['SPANDAU', 'Spandau'],
  ['STEGLITZ', 'Steglitz'],
  ['TEMPELHOF', 'Tempelhof'],
  ['TIERGARTEN', 'Tiergarten'],
  ['TREPTOW', 'Treptow'],
  ['WEDDING', 'Wedding'],
  ['WEISSENSEE', 'Weißensee'],
  ['WILMERSDORF', 'Wilmersdorf'],
  ['ZEHLENDORF', 'Zehlendorf'],
];
