# Generated by Django 2.1.3 on 2018-12-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("data", "0007_add_has_sticker")]

    operations = [
        migrations.AddField(
            model_name="gastro",
            name="submit_email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Submitter e-mail"
            ),
        )
    ]
