# Generated by Django 3.1.1 on 2020-09-25 22:26

from django.db import migrations


def charfield_null_to_empty_string(apps, schema_editor):
    Gastro = apps.get_model("data", "Gastro")
    Gastro.objects.all().filter(review_link__isnull=True).update(review_link="")
    Gastro.objects.all().filter(submit_email__isnull=True).update(submit_email="")


class Migration(migrations.Migration):

    dependencies = [("data", "0012_gastro_adjust_field_names")]

    operations = [
        migrations.RunPython(
            charfield_null_to_empty_string, reverse_code=migrations.RunPython.noop
        )
    ]
