# Generated by Django 5.1.1 on 2025-01-03 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import bvdata.data.models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0020_alter_baselocation_comment_public_transport_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="baselocation",
            name="comment_opening_hours",
            field=models.TextField(
                blank=True, default="", verbose_name="Comment Opening Hours"
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="tag",
            field=models.CharField(
                choices=[
                    ("foods", "Foods"),
                    ("clothing", "Clothing"),
                    ("toiletries", "Toiletries"),
                    ("supermarket", "Supermarket"),
                    ("hairdressers", "Hairdressers"),
                    ("sports", "Sports"),
                    ("tattoostudio", "Tattoostudio"),
                    ("accommodation", "Accommodation"),
                    ("bar", "Bar"),
                    ("cafe", "Coffee Shop"),
                    ("ice cream parlor", "Ice Cream Parlor"),
                    ("snack bar", "Snack Bar"),
                    ("restaurant", "Restaurant"),
                ],
                max_length=16,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        height_field="height",
                        upload_to=bvdata.data.models.image_upload_to,
                        width_field="width",
                    ),
                ),
                ("height", models.PositiveIntegerField()),
                ("width", models.PositiveIntegerField()),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.baselocation",
                    ),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
