name: Create and publish Docker image

on:
  workflow_dispatch:
  workflow_call:

env:
  REGISTRY: ghcr.io
  REPO: ${{ github.repository }}

jobs:
  backend-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build and Push BE image
        uses: ./.github/actions/build-push-image
        with:
          imageType: be
          imageContext: backend/
          repoToken: ${{ secrets.GITHUB_TOKEN }}

  frontend-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build and Push FE image
        uses: ./.github/actions/build-push-image
        with:
          imageType: fe
          imageContext: frontend/admin/
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          buildArgs: |
            REACT_APP_MAP_API_URL=${{ secrets.REACT_APP_MAP_API_URL }}
            REACT_APP_SENTRY_DSN=${{ secrets.REACT_APP_SENTRY_DSN }}
