name: Create and publish Docker image

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      REACT_APP_MAP_API_URL:
        required: true
      REACT_APP_SENTRY_DSN:
        required: true

env:
  REGISTRY: ghcr.io
  REPO: ${{ github.repository }}

jobs:
  backend-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build and Push BE image
        uses: ./.github/actions/build-push-image
        with:
          imageType: be
          imageContext: backend/
          repoToken: ${{ secrets.GITHUB_TOKEN }}

  frontend-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build and Push FE image
        uses: ./.github/actions/build-push-image
        with:
          imageType: fe
          imageContext: frontend/
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          buildArgs: |
            REACT_APP_MAP_API_URL=${{ secrets.REACT_APP_MAP_API_URL }}
            REACT_APP_SENTRY_DSN=${{ secrets.REACT_APP_SENTRY_DSN }}
